/**:
  ros__parameters:
    usingPowerManagementBoard: true
    verbosity: false
    canInterface: CAN2
    frequencyScale: 32
    inputWeight: 0.2
    maxPulseWidth: 100
    timeout: 300
    kp: 0.4
    ki: 4.0
    kd: 0.0
    antiWindup: 1
    responseMode: 0
    
    controllers: 2
    
    controller0:
      canID: 0
      drive0:
        channel: 0
        gearRatio: 70.0
        encoderRatio: 64.0
        rpmMax: 140.0
        invertEnc: 1
        kinematics: [20.0, 0.0, -6.1]
      drive1:
        channel: 1
        gearRatio: 70.0
        encoderRatio: 64.0
        rpmMax: 140.0
        invertEnc: 1
        kinematics: [-20.0, 0.0, -6.1]
  
    controller1:
      canID: 1
      drive0:
        channel: 0
        gearRatio: 70.0
        encoderRatio: 64.0
        rpmMax: 140.0
        invertEnc: 1
        kinematics: [20.0, 0.0, -6.1]
      drive1:
        channel: 1
        gearRatio: 70.0
        encoderRatio: 64.0
        rpmMax: 140.0
        invertEnc: 1
        kinematics: [-20.0, 0.0, -6.1]
